services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    restart: always
    command: ["node", "dist/server.js"]

  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    env_file:
        - ./db.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

